package GUI;
/** 
   por Rafael Ferreira Goulart
**/
public class JF_Menu extends javax.swing.JFrame {

    /**
     * Creates new form JF_Menu
     */
    public JF_Menu() {
        initComponents();
        setTitle("Menu");
        jTF_NomeJogador.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content   of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_Background = new javax.swing.JPanel();
        jP_InnerBackground = new javax.swing.JPanel();
        jL_Titulo = new javax.swing.JLabel();
        jSep_TituloMenu = new javax.swing.JSeparator();
        jL_NomeJogador = new javax.swing.JLabel();
        jTF_NomeJogador = new javax.swing.JTextField();
        jB_Jogar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Menu"); // NOI18N
        setResizable(false);

        jP_Background.setBackground(new java.awt.Color(0, 0, 0));

        jP_InnerBackground.setBackground(new java.awt.Color(102, 102, 102));

        jL_Titulo.setFont(new java.awt.Font("Felix Titling", 1, 48)); // NOI18N
        jL_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_Titulo.setText("Dr. Disease");

        jSep_TituloMenu.setBackground(new java.awt.Color(0, 0, 0));
        jSep_TituloMenu.setForeground(new java.awt.Color(0, 0, 0));
        jSep_TituloMenu.setOpaque(true);

        jL_NomeJogador.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jL_NomeJogador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_NomeJogador.setText("Nome do jogador:");

        jTF_NomeJogador.setBackground(new java.awt.Color(102, 102, 102));
        jTF_NomeJogador.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jTF_NomeJogador.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTF_NomeJogador.setText("Nickname");

        jB_Jogar.setBackground(new java.awt.Color(102, 102, 102));
        jB_Jogar.setFont(new java.awt.Font("Felix Titling", 1, 24)); // NOI18N
        jB_Jogar.setText("Jogar");
        jB_Jogar.setPreferredSize(new java.awt.Dimension(120, 40));
        jB_Jogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_JogarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_InnerBackgroundLayout = new javax.swing.GroupLayout(jP_InnerBackground);
        jP_InnerBackground.setLayout(jP_InnerBackgroundLayout);
        jP_InnerBackgroundLayout.setHorizontalGroup(
            jP_InnerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSep_TituloMenu)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_InnerBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jP_InnerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTF_NomeJogador)
                    .addComponent(jL_Titulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(jL_NomeJogador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jP_InnerBackgroundLayout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jB_Jogar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jP_InnerBackgroundLayout.setVerticalGroup(
            jP_InnerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_InnerBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSep_TituloMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jL_NomeJogador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTF_NomeJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jB_Jogar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout jP_BackgroundLayout = new javax.swing.GroupLayout(jP_Background);
        jP_Background.setLayout(jP_BackgroundLayout);
        jP_BackgroundLayout.setHorizontalGroup(
            jP_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_InnerBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jP_BackgroundLayout.setVerticalGroup(
            jP_BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jP_InnerBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jP_Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jB_JogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_JogarActionPerformed
        JF_Jogo abrir = new JF_Jogo();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jB_JogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Jogar;
    private javax.swing.JLabel jL_NomeJogador;
    private javax.swing.JLabel jL_Titulo;
    private javax.swing.JPanel jP_Background;
    private javax.swing.JPanel jP_InnerBackground;
    private javax.swing.JSeparator jSep_TituloMenu;
    private javax.swing.JTextField jTF_NomeJogador;
    // End of variables declaration//GEN-END:variables
}
